spring.application.name=nexverse
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show.sql=true
spring.jpa.properties.hibernate.format_sql=true
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.access-token-expiration=300000
#5 minutes (access token expiration)
security.jwt.refresh-token-expiration=86400000
#1 day (refresh token expiration)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
#spring.mail.port=587
#spring.mail.host=smtp.gmail.com
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
app.frontend.base-url=${FRONTEND_BASE_URL}
app.super-admin.email=${SUPER_ADMIN_EMAIL}
app.super-admin.password=${SUPER_ADMIN_PASSWORD}
logging.level.root=INFO
logging.file.name=logs/application.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
ftp.host=${FTP_HOST}
ftp.port=21
ftp.username=${FTP_USERNAME}
ftp.password=${FTP_PASSWORD}
ftp.base-directory=${FTP_BASE_DIRECTORY}
springdoc.cache.disabled=true
spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB
cookie.accessToken.maxAgeInMin=5
cookie.refreshToken.maxAgeInDays=1
file.validation.profile-image.max-size=2MB
file.validation.course-thumbnail.max-size=5MB
file.validation.course-content.pdf.max-size=100MB
file.validation.course-content.mp4.max-size=2GB
file.validation.skill-badge.max-size=1MB
file.validation.organization-logo.max-size=5MB